name: c360 refresh
on: 
    schedule:
        - cron: "0 0 1 1 *" # - cron: "*/5 * * * *"
    workflow_dispatch:

jobs:
    run_app:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checking Out Repo
          uses: actions/checkout@v2

        - name: Set Up Workflow
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Install Dependencies
          run: |
            pip install pandas
            pip install plotly
            pip install chart_studio
            pip install requests
            pip install datetime
        
        - name: Run C360
          env: 
            TOKEN: ${{ secrets.TOKEN }} 
            MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
            PLOTLY_TOKEN: ${{ secrets.PLOTLY_TOKEN }}
          run: python app.py


