name: c360 refresh
on: 
    schedule:
        - cron: "*/5 * * * *"
    workflow_dispatch:
      
jobs:
    run_app:
        runs-on: ubuntu-latest
        
        steps:
        - name: check code
          uses: actions/checkout@v2

        - name: set up python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        
        - name: run c360
          run: python app.py


